### PR TITLE
make fallthru to break, fixes compile error in gcc7

### PR DESCRIPTION
**Pull request by InuSasha**
now rebased on new master :)

### CODE REVIEW

**Comment by HiassofT** [comment]
To me it looks like this is missing a break - not sure why "-v" should enable "-f".

**Comment by InuSasha** [comment]
Nope.
verbose makes only sense, when running in foreground. The fall-through was intented by developer (not me)

**Comment by HiassofT** [comment]
Sure it was intended, any references? verbose variable only controls the setlogmask parameter (i.e. syslog stuff) - why should verbose syslog logging in background not be possible?

**Comment by InuSasha** [comment]
do not ask me :)
i keeped the old behavior and fixed the compiler message.
It looks like a wanted behavior.

**Comment by HiassofT** [comment]
I think gcc found a bug that went unnoticed for a really long time - missing breaks are quite common :)

As it's been this since the initial git commit, but not documented in the manpage and in general rather uncommon to do it this way a bug is IMO by far the most likely scenario.

**Pull request merged**
